import { LevelConfig, NoteDefinition } from '../types';

export const ALL_NOTES: Record<string, NoteDefinition> = {
  // ================= TREBLE CLEF (Right Hand) =================
  // Center line is B4 (staffPosition: 0)
  // Step size is 1 vertical step (line to space = 1, line to line = 2)
  'C4_treble': {
    id: 'C4_treble',
    pitch: 'C',
    octave: 4,
    clef: 'treble',
    staffPosition: -6, // Ledger line below staff
    isLine: true,
    mnemonicPhrase: 'Middle C (Secret Anchor)',
    mnemonicWord: 'Middle C',
    hand: 'right',
    frequency: 261.63,
  },
  'D4_treble': {
    id: 'D4_treble',
    pitch: 'D',
    octave: 4,
    clef: 'treble',
    staffPosition: -5, // Space below first line
    isLine: false,
    mnemonicPhrase: 'Just below the staff',
    mnemonicWord: 'Doorstep D',
    hand: 'right',
    frequency: 293.66,
  },
  'E4_treble': {
    id: 'E4_treble',
    pitch: 'E',
    octave: 4,
    clef: 'treble',
    staffPosition: -4, // Line 1
    isLine: true,
    mnemonicPhrase: 'Every Good Boy Deserves Fudge',
    mnemonicWord: 'Every',
    hand: 'right',
    frequency: 329.63,
  },
  'F4_treble': {
    id: 'F4_treble',
    pitch: 'F',
    octave: 4,
    clef: 'treble',
    staffPosition: -3, // Space 1
    isLine: false,
    mnemonicPhrase: 'F - A - C - E',
    mnemonicWord: 'F',
    hand: 'right',
    frequency: 349.23,
  },
  'G4_treble': {
    id: 'G4_treble',
    pitch: 'G',
    octave: 4,
    clef: 'treble',
    staffPosition: -2, // Line 2
    isLine: true,
    mnemonicPhrase: 'Every Good Boy Deserves Fudge',
    mnemonicWord: 'Good',
    hand: 'right',
    frequency: 392.00,
  },
  'A4_treble': {
    id: 'A4_treble',
    pitch: 'A',
    octave: 4,
    clef: 'treble',
    staffPosition: -1, // Space 2
    isLine: false,
    mnemonicPhrase: 'F - A - C - E',
    mnemonicWord: 'A',
    hand: 'right',
    frequency: 440.00,
  },
  'B4_treble': {
    id: 'B4_treble',
    pitch: 'B',
    octave: 4,
    clef: 'treble',
    staffPosition: 0, // Line 3 (Middle line)
    isLine: true,
    mnemonicPhrase: 'Every Good Boy Deserves Fudge',
    mnemonicWord: 'Boy',
    hand: 'right',
    frequency: 493.88,
  },
  'C5_treble': {
    id: 'C5_treble',
    pitch: 'C',
    octave: 5,
    clef: 'treble',
    staffPosition: 1, // Space 3
    isLine: false,
    mnemonicPhrase: 'F - A - C - E',
    mnemonicWord: 'C',
    hand: 'right',
    frequency: 523.25,
  },
  'D5_treble': {
    id: 'D5_treble',
    pitch: 'D',
    octave: 5,
    clef: 'treble',
    staffPosition: 2, // Line 4
    isLine: true,
    mnemonicPhrase: 'Every Good Boy Deserves Fudge',
    mnemonicWord: 'Deserves',
    hand: 'right',
    frequency: 587.33,
  },
  'E5_treble': {
    id: 'E5_treble',
    pitch: 'E',
    octave: 5,
    clef: 'treble',
    staffPosition: 3, // Space 4
    isLine: false,
    mnemonicPhrase: 'F - A - C - E',
    mnemonicWord: 'E',
    hand: 'right',
    frequency: 659.25,
  },
  'F5_treble': {
    id: 'F5_treble',
    pitch: 'F',
    octave: 5,
    clef: 'treble',
    staffPosition: 4, // Line 5
    isLine: true,
    mnemonicPhrase: 'Every Good Boy Deserves Fudge',
    mnemonicWord: 'Fudge',
    hand: 'right',
    frequency: 698.46,
  },
  'G5_treble': {
    id: 'G5_treble',
    pitch: 'G',
    octave: 5,
    clef: 'treble',
    staffPosition: 5, // Space above top line
    isLine: false,
    mnemonicPhrase: 'Sitting on top of the staff',
    mnemonicWord: 'Grand G',
    hand: 'right',
    frequency: 783.99,
  },

  // ================= BASS CLEF (Left Hand) =================
  // Center line is D3 (staffPosition: 0)
  'F2_bass': {
    id: 'F2_bass',
    pitch: 'F',
    octave: 2,
    clef: 'bass',
    staffPosition: -5, // Space below line 1
    isLine: false,
    mnemonicPhrase: 'Floor F',
    mnemonicWord: 'Floor F',
    hand: 'left',
    frequency: 87.31,
  },
  'G2_bass': {
    id: 'G2_bass',
    pitch: 'G',
    octave: 2,
    clef: 'bass',
    staffPosition: -4, // Line 1
    isLine: true,
    mnemonicPhrase: 'Green Bears Don\'t Fly Airplanes',
    mnemonicWord: 'Green',
    hand: 'left',
    frequency: 98.00,
  },
  'A2_bass': {
    id: 'A2_bass',
    pitch: 'A',
    octave: 2,
    clef: 'bass',
    staffPosition: -3, // Space 1
    isLine: false,
    mnemonicPhrase: 'All Cows Eat Grass',
    mnemonicWord: 'All',
    hand: 'left',
    frequency: 110.00,
  },
  'B2_bass': {
    id: 'B2_bass',
    pitch: 'B',
    octave: 2,
    clef: 'bass',
    staffPosition: -2, // Line 2
    isLine: true,
    mnemonicPhrase: 'Green Bears Don\'t Fly Airplanes',
    mnemonicWord: 'Bears',
    hand: 'left',
    frequency: 123.47,
  },
  'C3_bass': {
    id: 'C3_bass',
    pitch: 'C',
    octave: 3,
    clef: 'bass',
    staffPosition: -1, // Space 2
    isLine: false,
    mnemonicPhrase: 'All Cows Eat Grass',
    mnemonicWord: 'Cows',
    hand: 'left',
    frequency: 130.81,
  },
  'D3_bass': {
    id: 'D3_bass',
    pitch: 'D',
    octave: 3,
    clef: 'bass',
    staffPosition: 0, // Line 3 (Middle line)
    isLine: true,
    mnemonicPhrase: 'Green Bears Don\'t Fly Airplanes',
    mnemonicWord: 'Don\'t',
    hand: 'left',
    frequency: 146.83,
  },
  'E3_bass': {
    id: 'E3_bass',
    pitch: 'E',
    octave: 3,
    clef: 'bass',
    staffPosition: 1, // Space 3
    isLine: false,
    mnemonicPhrase: 'All Cows Eat Grass',
    mnemonicWord: 'Eat',
    hand: 'left',
    frequency: 164.81,
  },
  'F3_bass': {
    id: 'F3_bass',
    pitch: 'F',
    octave: 3,
    clef: 'bass',
    staffPosition: 2, // Line 4
    isLine: true,
    mnemonicPhrase: 'Green Bears Don\'t Fly Airplanes',
    mnemonicWord: 'Fly',
    hand: 'left',
    frequency: 174.61,
  },
  'G3_bass': {
    id: 'G3_bass',
    pitch: 'G',
    octave: 3,
    clef: 'bass',
    staffPosition: 3, // Space 4
    isLine: false,
    mnemonicPhrase: 'All Cows Eat Grass',
    mnemonicWord: 'Grass',
    hand: 'left',
    frequency: 196.00,
  },
  'A3_bass': {
    id: 'A3_bass',
    pitch: 'A',
    octave: 3,
    clef: 'bass',
    staffPosition: 4, // Line 5
    isLine: true,
    mnemonicPhrase: 'Green Bears Don\'t Fly Airplanes',
    mnemonicWord: 'Airplanes',
    hand: 'left',
    frequency: 220.00,
  },
  'B3_bass': {
    id: 'B3_bass',
    pitch: 'B',
    octave: 3,
    clef: 'bass',
    staffPosition: 5, // Space above top line
    isLine: false,
    mnemonicPhrase: 'Just above bass staff',
    mnemonicWord: 'Balcony B',
    hand: 'left',
    frequency: 246.94,
  },
  'C4_bass': {
    id: 'C4_bass',
    pitch: 'C',
    octave: 4,
    clef: 'bass',
    staffPosition: 6, // Ledger line above bass staff
    isLine: true,
    mnemonicPhrase: 'Middle C (Secret Bridge)',
    mnemonicWord: 'Middle C',
    hand: 'left',
    frequency: 261.63,
  },
};

export const LEVELS: LevelConfig[] = [
  {
    id: 1,
    title: 'Treble Spaces: F-A-C-E',
    clef: 'treble',
    description: 'Learn the 4 notes between the lines on the Treble Clef (Right Hand). They spell FACE!',
    mnemonicFocus: 'F - A - C - E',
    mnemonicRule: 'Spaces on Treble Clef spell FACE from bottom to top!',
    noteIds: ['F4_treble', 'A4_treble', 'C5_treble', 'E5_treble'],
    totalNotes: 8,
    minAccuracyToPass: 75,
    badgeName: 'Treble Face Explorer',
  },
  {
    id: 2,
    title: 'Treble Lines: Every Good Boy Deserves Fudge',
    clef: 'treble',
    description: 'Learn the 5 lines of the Treble Clef! Remember: E-G-B-D-F.',
    mnemonicFocus: 'Every Good Boy Deserves Fudge',
    mnemonicRule: 'Lines on Treble Clef: E (Every), G (Good), B (Boy), D (Deserves), F (Fudge)!',
    noteIds: ['E4_treble', 'G4_treble', 'B4_treble', 'D5_treble', 'F5_treble'],
    totalNotes: 10,
    minAccuracyToPass: 70,
    badgeName: 'Fudge Detective',
  },
  {
    id: 3,
    title: 'Treble Clef Master & Middle C',
    clef: 'treble',
    description: 'Combine all lines & spaces on Treble Clef, plus Middle C!',
    mnemonicFocus: 'FACE + Every Good Boy Deserves Fudge',
    mnemonicRule: 'Lines: EGBDF | Spaces: FACE | Middle C sits on its own little line below!',
    noteIds: [
      'C4_treble', 'D4_treble', 'E4_treble', 'F4_treble',
      'G4_treble', 'A4_treble', 'B4_treble', 'C5_treble',
      'D5_treble', 'E5_treble', 'F5_treble', 'G5_treble'
    ],
    totalNotes: 12,
    minAccuracyToPass: 75,
    badgeName: 'Treble Virtuoso',
  },
  {
    id: 4,
    title: 'Bass Spaces: All Cows Eat Grass',
    clef: 'bass',
    description: 'Explore the Left Hand spaces on Bass Clef! A-C-E-G.',
    mnemonicFocus: 'All Cows Eat Grass',
    mnemonicRule: 'Spaces on Bass Clef: A (All), C (Cows), E (Eat), G (Grass)!',
    noteIds: ['A2_bass', 'C3_bass', 'E3_bass', 'G3_bass'],
    totalNotes: 8,
    minAccuracyToPass: 75,
    badgeName: 'Cow Pasture Ranger',
  },
  {
    id: 5,
    title: 'Bass Lines: Green Bears Don\'t Fly Airplanes',
    clef: 'bass',
    description: 'Master the 5 lines of the Bass Clef! G-B-D-F-A.',
    mnemonicFocus: 'Green Bears Don\'t Fly Airplanes',
    mnemonicRule: 'Lines on Bass Clef: G (Green), B (Bears), D (Don\'t), F (Fly), A (Airplanes)!',
    noteIds: ['G2_bass', 'B2_bass', 'D3_bass', 'F3_bass', 'A3_bass'],
    totalNotes: 10,
    minAccuracyToPass: 70,
    badgeName: 'Green Bear Pilot',
  },
  {
    id: 6,
    title: 'Bass Clef Master & Middle C',
    clef: 'bass',
    description: 'All lines and spaces for the Left Hand on Bass Clef, plus Middle C!',
    mnemonicFocus: 'Green Bears + All Cows Eat Grass',
    mnemonicRule: 'Lines: GBDFA | Spaces: ACEG | Middle C sits on the line above!',
    noteIds: [
      'F2_bass', 'G2_bass', 'A2_bass', 'B2_bass',
      'C3_bass', 'D3_bass', 'E3_bass', 'F3_bass',
      'G3_bass', 'A3_bass', 'B3_bass', 'C4_bass'
    ],
    totalNotes: 12,
    minAccuracyToPass: 75,
    badgeName: 'Bass Commander',
  },
  {
    id: 7,
    title: 'Grand Staff Hero (Both Hands Mixed!)',
    clef: 'mixed',
    description: 'Switch between Treble (Right Hand) and Bass (Left Hand) smoothly!',
    mnemonicFocus: 'All 4 Memory Tricks',
    mnemonicRule: 'Look at the Clef first! 𝄞 = Treble (RH), 𝄢 = Bass (LH).',
    noteIds: [
      'C4_treble', 'E4_treble', 'F4_treble', 'G4_treble', 'A4_treble', 'B4_treble', 'C5_treble',
      'C4_bass', 'G2_bass', 'A2_bass', 'C3_bass', 'D3_bass', 'E3_bass', 'F3_bass', 'G3_bass'
    ],
    totalNotes: 14,
    minAccuracyToPass: 80,
    badgeName: 'Grand Staff Hero',
  },
  {
    id: 8,
    title: 'Speed Lightning Challenge',
    clef: 'mixed',
    description: 'Answer as fast as you can to score high speed bonuses and gold stars!',
    mnemonicFocus: 'Lightning Speed Reflexes',
    mnemonicRule: 'Fast answers under 2 seconds get massive speed bonus points!',
    noteIds: [
      'C4_treble', 'D4_treble', 'E4_treble', 'F4_treble', 'G4_treble', 'A4_treble', 'B4_treble', 'C5_treble', 'D5_treble', 'E5_treble', 'F5_treble',
      'G2_bass', 'A2_bass', 'B2_bass', 'C3_bass', 'D3_bass', 'E3_bass', 'F3_bass', 'G3_bass', 'A3_bass', 'C4_bass'
    ],
    totalNotes: 15,
    timeLimitSec: 6,
    minAccuracyToPass: 80,
    badgeName: 'Grand Maestro Legend',
  },
];

export const MNEMONIC_GUIDE_DATA = {
  treble: {
    clefName: 'Treble Clef (Right Hand 𝄞)',
    spaces: {
      rule: 'F - A - C - E',
      description: 'The notes between the lines spell the word FACE from bottom to top!',
      items: [
        { note: 'F', word: 'F', position: 'Space 1 (Bottom)' },
        { note: 'A', word: 'A', position: 'Space 2' },
        { note: 'C', word: 'C', position: 'Space 3' },
        { note: 'E', word: 'E', position: 'Space 4 (Top)' },
      ],
    },
    lines: {
      rule: 'Every Good Boy Deserves Fudge',
      description: 'The 5 lines from bottom to top:',
      items: [
        { note: 'E', word: 'Every', position: 'Line 1 (Bottom)' },
        { note: 'G', word: 'Good', position: 'Line 2' },
        { note: 'B', word: 'Boy', position: 'Line 3' },
        { note: 'D', word: 'Deserves', position: 'Line 4' },
        { note: 'F', word: 'Fudge', position: 'Line 5 (Top)' },
      ],
    },
  },
  bass: {
    clefName: 'Bass Clef (Left Hand 𝄢)',
    lines: {
      rule: 'Green Bears Don\'t Fly Airplanes',
      description: 'The 5 lines from bottom to top:',
      items: [
        { note: 'G', word: 'Green', position: 'Line 1 (Bottom)' },
        { note: 'B', word: 'Bears', position: 'Line 2' },
        { note: 'D', word: 'Don\'t', position: 'Line 3' },
        { note: 'F', word: 'Fly', position: 'Line 4' },
        { note: 'A', word: 'Airplanes', position: 'Line 5 (Top)' },
      ],
    },
    spaces: {
      rule: 'All Cows Eat Grass',
      description: 'The notes between the lines from bottom to top:',
      items: [
        { note: 'A', word: 'All', position: 'Space 1 (Bottom)' },
        { note: 'C', word: 'Cows', position: 'Space 2' },
        { note: 'E', word: 'Eat', position: 'Space 3' },
        { note: 'G', word: 'Grass', position: 'Space 4 (Top)' },
      ],
    },
  },
};
